import {
  PRO_BACKEND_HOST,
  PRO_ADAFRUIT_USER,
  PRO_ADAFRUIT_KEY,
  PRO_ADAFRUIT_TOPIC_PREFIX,
  DEV_BACKEND_HOST,
  DEV_ADAFRUIT_USER,
  DEV_ADAFRUIT_KEY,
  DEV_ADAFRUIT_TOPIC_PREFIX,
  NODE_ENV,
} from '@env'

const configs = {
  pro: {
    BACKEND_HOST: PRO_BACKEND_HOST,
    ADAFRUIT_USER: PRO_ADAFRUIT_USER,
    ADAFRUIT_KEY: PRO_ADAFRUIT_KEY,
    ADAFRUIT_TOPIC_PREFIX: PRO_ADAFRUIT_TOPIC_PREFIX,
  },
  dev: {
    BACKEND_HOST: DEV_BACKEND_HOST,
    ADAFRUIT_USER: DEV_ADAFRUIT_USER,
    ADAFRUIT_KEY: DEV_ADAFRUIT_KEY,
    ADAFRUIT_TOPIC_PREFIX: PRO_ADAFRUIT_TOPIC_PREFIX,
  },
}

const env = NODE_ENV == 'pro' ? 'pro' : 'dev'
console.log(env)
console.log(configs[env])
export default configs[env]
